### ISSUE TITLE
Compatibility with Devise

### ISSUE THREAD

**Issue by rabidaudio** [convox-examples/rails#5]
I was running into some issues with the asset compilation step when trying to convert an existing rails app. Turns out when rake initializes the app, it initializes `routes.rb`. My application is using [devise](https://github.com/plataformatec/devise), and the `devise_for` method of needs a database connection. However, the database isn't linked until after the build completes.

One dirty solution in this case would be to move asset compilation to the application start command rather than part of the build process.

Another solution (the one I ended up going with) is creating another environment (`tasks`) with a sqlite database and adjusting the `Dockerfile`:

```
RUN RAILS_ENV=tasks DATABASE_URL=sqlite3:///app/db/tasks.sqlite3 rake assets:precompile
```

And then adding this hack to my `routes.rb`:

``` ruby
  def devise_for *args
    super args unless Rails.env.tasks?
  end
```

I'm open to other ideas or suggestions. I'm also happy to update the docs.

**Comment by matthewford** [comment]
You can just set a fake db connection e.g. `ENV DATABASE_URL postgresql://localhost/dummy_url` before the asset compilation
